name: vscode extension
on:
  push:
    branches:
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VSCODE_PUBLISHER_TOKEN: ${{ secrets.VSCODE_PUBLISHER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn
      - name: Build package
        run: yarn package

      # Staging
      - name: Upload package to next folder
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.SPACES_KEY}}
          secret_key: ${{ secrets.SPACES_SECRET }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: aleo-instructions-syntax.vsix
          out_dir: vscode-extension/next
      
      # Production
      - name: Upload package to latest folder
        if: startsWith(github.ref, 'refs/tags/')
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.SPACES_KEY}}
          secret_key: ${{ secrets.SPACES_SECRET }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: aleo-instructions-syntax.vsix
          out_dir: vscode-extension/latest
      - name: Upload package to version folder
        if: startsWith(github.ref, 'refs/tags/')
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.SPACES_KEY}}
          secret_key: ${{ secrets.SPACES_SECRET }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: aleo-instructions-syntax.vsix
          out_dir: vscode-extension/${{steps.parse_version.outputs.version}}
      - name: Publish to market
        if: startsWith(github.ref, 'refs/tags/')
        run: yarn publish-to-market
